---
title: "Highlights"
format: html
---

Highlights:

- 15-minute neighbourhoods (FMN) have (re)-emerged as a popular concept in urban-planning city-planning; emphasizing the access to urban amenities by foot or bicycle. However, historically, neighbourhood planning processes have been top-down; FMC is linked to the Neighbourhood Unit Concept of the 1920s, largely critized for supporting segregated neighbourhoods, leaving a void in neighbourhood planning concepts that were filled by auto-centric suburban sprawl. Regardless, fundamental concepts within FMC remain popular: people identify with neighbourhoods, see cities through that lense. These ideas have in part re-emerged in the popularity of 15-minute neighbourhoods. 

- But how do we uplift the positive, popular, aspects of FMN without opening it up to the critics of the NUC? In this work, we turn to feminist geographies and the Mobility of Care conceptualisation and apply it to FMC. We argue, conventional planning practice is masculinist. This can threaten the FMC concept by shaping how 'important' amenities are conceptualised thus favouring work- and leisure- centered amenities in cities that are increasingly capital-driven. Though FMN is fundamentally based in bottom-up collaborative planning processes, we exist in the context of planning pracice which is largely masculinist. 

- FMN are for people - people do unpaid labour, those people are often women and intersectionally women-of-colour and low-income. However, this work should be for all people. Cities should be designed with this conceptualisation in mind. This is to combate the growing capitalisation of cities. 

- Our paper offers this nuanced understanding of FNC -- calling for them to center Care Destinations as important amenity types with the explicit conceptualisation that their destination type matters especially for women (low-income and of colour) who interact with them most, but also for all people. Their explicit positioning also can indirectly combat finacialisation of cities and co-opting of the FMC concept to one that centers capital-generating destination types like work and prohibitive leisure. Not to say those destination types should or cannot co-exist with Care destinations -- they should -- but markets are already incentivizing them. The market does not speak for non-economically geberating destination types, so we must explicitly call for them and support them within the FNC framework. 
- 
- 
- 